version: '3'

services:
  database:
    image: postgres
    container_name: postgres_demo
    restart: always
    env_file:
      - database.env
    ports:
      - 5434:5432
    volumes:
      - cats-db-data:/var/lib/postgresql/data/

volumes:
  cats-db-data:
